# Test the batoms plugin using test
name: Test batoms-api package

on:
  push:
    branches:
      - main
      - develop
      - workflow
  pull_request:
    branches:
      - main
      - develop
      - workflow
  workflow_dispatch:

env:
  TEST_IMAGE_NAME: ghcr.io/beautiful-atoms/blender-env

jobs:
  basic:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Manually change these to match the blender image versions
        blender-version: ["3.0", "3.1", "3.2"]
    container:
      image: ghcr.io/beautiful-atoms/beautiful-atoms:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest batoms-api and test dependencies
        run: |
          $BLENDERPY -m pip install pytest==6.2.5 flake8 pytest-blender &&\
          $BLENDERPY -m pip install .
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --exclude=batoms_api/script-api.py,batoms_api/api --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --exclude=batoms_api/script-api.py,batoms_api/api --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
